version: '3'

services:
  prosody:
    image: prosody/prosody
    container_name: prosody
    environment:
      - LOCAL=admin
      - DOMAIN=localhost
      - PASSWORD=admin
      - ADMIN_TELNET_ENABLED=true
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5347:5347"
    volumes:
      - ./prosody/logs:/var/log/prosody
      - ./prosody/modules:/usr/lib/prosody-modules
      - ./prosody/certs:/usr/local/etc/prosody/certs
    restart: always
